### ISSUE TITLE
getImages

### ISSUE THREAD

**Issue by ZaYtI** [luvlqq/nestjs-googledrive#1]
I want to display an image on my website using the getImage method, but I believe the getImages method returns an invalid link.

The link provided is: https://drive.google.com/uc?id=https://drive.google.com/uc?id=1PU8l8VOQ5vH1yXR2jEE-qurqFaD-urLI. However, this link does not exist on Google Drive, so I cannot use it to display the image on the frontend.

**Comment by luvlqq** [comment]
hey @ZaYtI ! Strange, the link should be different. I updated the package to version 2.0.0. Now the link looks different. You should also check if your folder on Google Drive is open for viewing by any user.

**Comment by ZaYtI** [comment]
I don't know if it's possible to have a direct link to the file that would allow me to place the link in an HTML img tag and have it display correctly. For this, I found a little workaround. I don't think it's a good long-term solution, but it works.

if you keep the id in the link and use the id in this url it works:

https://drive.google.com/thumbnail?id={IMAGE-ID}&sz=w1000

The addition of "sz=w1000" at the end is used to achieve better image quality by loading it in a larger size.

**Comment by luvlqq** [comment]
Yes, that solution is correct. In the new version of my library, such a link is generated. However, it does not include "sz=w1000" anymore. You can add it yourself using a template string or concatenation.
